import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import time

print("Downloading model")
start = time.perf_counter()

model_id = "BAAI/bge-reranker-base"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSequenceClassification.from_pretrained(model_id)
model.eval()

# Dynamic quantization (CPU only)  
model = torch.quantization.quantize_dynamic(  
    model, {torch.nn.Linear}, dtype=torch.qint8  
) 

end = time.perf_counter()  
elapsed = end - start  
print(f"Downloaded in {elapsed:.2f} seconds")

print("Download complete. Running reranker...")
start = time.perf_counter()

pairs = [
    [
        "What is the capital of China?",
        "The capital of China is Beijing."
    ],
    [
        "Explain gravity",
        "Gravity is a force that attracts two bodies towards each other. It gives weight to physical objects and is responsible for the movement of planets around the sun."
    ],
    [
        "what is a constituent entity?",
        "The term Constituent Entity defines those Group Entities that are subject to the GloBE Rules. For example, a Group Entity must be a Constituent Entity before it can be treated as an LTCE and subject to charge under the IIR or UTPR, under Chapters 2 to 5 of the rules."
    ],
    [
        "What is financial accounting net income or loss?",
        "The GloBE Income or Loss of each Constituent Entity is the Financial Accounting Net Income or Loss determined for the Constituent Entity for the Fiscal Year adjusted for the items described in Article 3.2 to Article 3.5. Financial Accounting Net Income or Loss is the net income or loss determined for a Constituent Entity (before any consolidation adjustments eliminating intra-group transactions) in preparing Consolidated Financial Statements of the Ultimate Parent Entity. If it is not reasonably practicable to determine the Financial Accounting Net Income or Loss for a Constituent Entity based on the accounting standard used in the preparation of Consolidated Financial Statements of the Ultimate Parent Entity, the Financial Accounting Net Income or Loss for the Constituent Entity for the Fiscal Year may be determined using another Acceptable Financial Accounting Standard or an Authorised Financial Accounting Standard if: (a) the financial accounts of the Constituent Entity are maintained based on that accounting standard; (b) the information contained in the financial accounts is reliable; and (c) permanent differences in excess of EUR 1 million that arise from the application of a particular principle or standard to items of income or expense or transactions that differs from the financial standard used in the preparation of the Consolidated Financial Statements of the Ultimate Parent Entity are conformed to the treatment required under the accounting standard used in the Consolidated Financial Statements of the Ultimate Parent Entity."
    ],
    [
        "What is financial accounting net income or loss?",
        "The GloBE Income or Loss of each Constituent Entity is the Financial Accounting Net Income or Loss determined for the Constituent Entity for the Fiscal Year adjusted for the items described in Article 3.2 to Article 3.5. Financial Accounting Net Income or Loss is the net income or loss determined for a Constituent Entity (before any consolidation adjustments eliminating intra-group transactions) in preparing Consolidated Financial Statements of the Ultimate Parent Entity. If it is not reasonably practicable to determine the Financial Accounting Net Income or Loss for a Constituent Entity based on the accounting standard used in the preparation of Consolidated Financial Statements of the Ultimate Parent Entity, the Financial Accounting Net Income or Loss for the Constituent Entity for the Fiscal Year may be determined using another Acceptable Financial Accounting Standard or an Authorised Financial Accounting Standard if: (a) the financial accounts of the Constituent Entity are maintained based on that accounting standard; (b) the information contained in the financial accounts is reliable; and (c) permanent differences in excess of EUR 1 million that arise from the application of a particular principle or standard to items of income or expense or transactions that differs from the financial standard used in the preparation of the Consolidated Financial Statements of the Ultimate Parent Entity are conformed to the treatment required under the accounting standard used in the Consolidated Financial Statements of the Ultimate Parent Entity."
    ],
    [
        "What is financial accounting net income or loss?",
        "The GloBE Income or Loss of each Constituent Entity is the Financial Accounting Net Income or Loss determined for the Constituent Entity for the Fiscal Year adjusted for the items described in Article 3.2 to Article 3.5. Financial Accounting Net Income or Loss is the net income or loss determined for a Constituent Entity (before any consolidation adjustments eliminating intra-group transactions) in preparing Consolidated Financial Statements of the Ultimate Parent Entity. If it is not reasonably practicable to determine the Financial Accounting Net Income or Loss for a Constituent Entity based on the accounting standard used in the preparation of Consolidated Financial Statements of the Ultimate Parent Entity, the Financial Accounting Net Income or Loss for the Constituent Entity for the Fiscal Year may be determined using another Acceptable Financial Accounting Standard or an Authorised Financial Accounting Standard if: (a) the financial accounts of the Constituent Entity are maintained based on that accounting standard; (b) the information contained in the financial accounts is reliable; and (c) permanent differences in excess of EUR 1 million that arise from the application of a particular principle or standard to items of income or expense or transactions that differs from the financial standard used in the preparation of the Consolidated Financial Statements of the Ultimate Parent Entity are conformed to the treatment required under the accounting standard used in the Consolidated Financial Statements of the Ultimate Parent Entity."
    ],
    [
        "What is financial accounting net income or loss?",
        "The GloBE Income or Loss of each Constituent Entity is the Financial Accounting Net Income or Loss determined for the Constituent Entity for the Fiscal Year adjusted for the items described in Article 3.2 to Article 3.5. Financial Accounting Net Income or Loss is the net income or loss determined for a Constituent Entity (before any consolidation adjustments eliminating intra-group transactions) in preparing Consolidated Financial Statements of the Ultimate Parent Entity. If it is not reasonably practicable to determine the Financial Accounting Net Income or Loss for a Constituent Entity based on the accounting standard used in the preparation of Consolidated Financial Statements of the Ultimate Parent Entity, the Financial Accounting Net Income or Loss for the Constituent Entity for the Fiscal Year may be determined using another Acceptable Financial Accounting Standard or an Authorised Financial Accounting Standard if: (a) the financial accounts of the Constituent Entity are maintained based on that accounting standard; (b) the information contained in the financial accounts is reliable; and (c) permanent differences in excess of EUR 1 million that arise from the application of a particular principle or standard to items of income or expense or transactions that differs from the financial standard used in the preparation of the Consolidated Financial Statements of the Ultimate Parent Entity are conformed to the treatment required under the accounting standard used in the Consolidated Financial Statements of the Ultimate Parent Entity."
    ],
    [
        "What is financial accounting net income or loss?",
        "The GloBE Income or Loss of each Constituent Entity is the Financial Accounting Net Income or Loss determined for the Constituent Entity for the Fiscal Year adjusted for the items described in Article 3.2 to Article 3.5. Financial Accounting Net Income or Loss is the net income or loss determined for a Constituent Entity (before any consolidation adjustments eliminating intra-group transactions) in preparing Consolidated Financial Statements of the Ultimate Parent Entity. If it is not reasonably practicable to determine the Financial Accounting Net Income or Loss for a Constituent Entity based on the accounting standard used in the preparation of Consolidated Financial Statements of the Ultimate Parent Entity, the Financial Accounting Net Income or Loss for the Constituent Entity for the Fiscal Year may be determined using another Acceptable Financial Accounting Standard or an Authorised Financial Accounting Standard if: (a) the financial accounts of the Constituent Entity are maintained based on that accounting standard; (b) the information contained in the financial accounts is reliable; and (c) permanent differences in excess of EUR 1 million that arise from the application of a particular principle or standard to items of income or expense or transactions that differs from the financial standard used in the preparation of the Consolidated Financial Statements of the Ultimate Parent Entity are conformed to the treatment required under the accounting standard used in the Consolidated Financial Statements of the Ultimate Parent Entity."
    ],
    [
        "What is financial accounting net income or loss?",
        "The GloBE Income or Loss of each Constituent Entity is the Financial Accounting Net Income or Loss determined for the Constituent Entity for the Fiscal Year adjusted for the items described in Article 3.2 to Article 3.5. Financial Accounting Net Income or Loss is the net income or loss determined for a Constituent Entity (before any consolidation adjustments eliminating intra-group transactions) in preparing Consolidated Financial Statements of the Ultimate Parent Entity. If it is not reasonably practicable to determine the Financial Accounting Net Income or Loss for a Constituent Entity based on the accounting standard used in the preparation of Consolidated Financial Statements of the Ultimate Parent Entity, the Financial Accounting Net Income or Loss for the Constituent Entity for the Fiscal Year may be determined using another Acceptable Financial Accounting Standard or an Authorised Financial Accounting Standard if: (a) the financial accounts of the Constituent Entity are maintained based on that accounting standard; (b) the information contained in the financial accounts is reliable; and (c) permanent differences in excess of EUR 1 million that arise from the application of a particular principle or standard to items of income or expense or transactions that differs from the financial standard used in the preparation of the Consolidated Financial Statements of the Ultimate Parent Entity are conformed to the treatment required under the accounting standard used in the Consolidated Financial Statements of the Ultimate Parent Entity."
    ],
    [
        "What is financial accounting net income or loss?",
        "The GloBE Income or Loss of each Constituent Entity is the Financial Accounting Net Income or Loss determined for the Constituent Entity for the Fiscal Year adjusted for the items described in Article 3.2 to Article 3.5. Financial Accounting Net Income or Loss is the net income or loss determined for a Constituent Entity (before any consolidation adjustments eliminating intra-group transactions) in preparing Consolidated Financial Statements of the Ultimate Parent Entity. If it is not reasonably practicable to determine the Financial Accounting Net Income or Loss for a Constituent Entity based on the accounting standard used in the preparation of Consolidated Financial Statements of the Ultimate Parent Entity, the Financial Accounting Net Income or Loss for the Constituent Entity for the Fiscal Year may be determined using another Acceptable Financial Accounting Standard or an Authorised Financial Accounting Standard if: (a) the financial accounts of the Constituent Entity are maintained based on that accounting standard; (b) the information contained in the financial accounts is reliable; and (c) permanent differences in excess of EUR 1 million that arise from the application of a particular principle or standard to items of income or expense or transactions that differs from the financial standard used in the preparation of the Consolidated Financial Statements of the Ultimate Parent Entity are conformed to the treatment required under the accounting standard used in the Consolidated Financial Statements of the Ultimate Parent Entity."
    ],
    [
        "What is financial accounting net income or loss?",
        "The GloBE Income or Loss of each Constituent Entity is the Financial Accounting Net Income or Loss determined for the Constituent Entity for the Fiscal Year adjusted for the items described in Article 3.2 to Article 3.5. Financial Accounting Net Income or Loss is the net income or loss determined for a Constituent Entity (before any consolidation adjustments eliminating intra-group transactions) in preparing Consolidated Financial Statements of the Ultimate Parent Entity. If it is not reasonably practicable to determine the Financial Accounting Net Income or Loss for a Constituent Entity based on the accounting standard used in the preparation of Consolidated Financial Statements of the Ultimate Parent Entity, the Financial Accounting Net Income or Loss for the Constituent Entity for the Fiscal Year may be determined using another Acceptable Financial Accounting Standard or an Authorised Financial Accounting Standard if: (a) the financial accounts of the Constituent Entity are maintained based on that accounting standard; (b) the information contained in the financial accounts is reliable; and (c) permanent differences in excess of EUR 1 million that arise from the application of a particular principle or standard to items of income or expense or transactions that differs from the financial standard used in the preparation of the Consolidated Financial Statements of the Ultimate Parent Entity are conformed to the treatment required under the accounting standard used in the Consolidated Financial Statements of the Ultimate Parent Entity."
    ],
    [
        "What is financial accounting net income or loss?",
        "The GloBE Income or Loss of each Constituent Entity is the Financial Accounting Net Income or Loss determined for the Constituent Entity for the Fiscal Year adjusted for the items described in Article 3.2 to Article 3.5. Financial Accounting Net Income or Loss is the net income or loss determined for a Constituent Entity (before any consolidation adjustments eliminating intra-group transactions) in preparing Consolidated Financial Statements of the Ultimate Parent Entity. If it is not reasonably practicable to determine the Financial Accounting Net Income or Loss for a Constituent Entity based on the accounting standard used in the preparation of Consolidated Financial Statements of the Ultimate Parent Entity, the Financial Accounting Net Income or Loss for the Constituent Entity for the Fiscal Year may be determined using another Acceptable Financial Accounting Standard or an Authorised Financial Accounting Standard if: (a) the financial accounts of the Constituent Entity are maintained based on that accounting standard; (b) the information contained in the financial accounts is reliable; and (c) permanent differences in excess of EUR 1 million that arise from the application of a particular principle or standard to items of income or expense or transactions that differs from the financial standard used in the preparation of the Consolidated Financial Statements of the Ultimate Parent Entity are conformed to the treatment required under the accounting standard used in the Consolidated Financial Statements of the Ultimate Parent Entity."
    ],
    [
        "What is financial accounting net income or loss?",
        "The GloBE Income or Loss of each Constituent Entity is the Financial Accounting Net Income or Loss determined for the Constituent Entity for the Fiscal Year adjusted for the items described in Article 3.2 to Article 3.5. Financial Accounting Net Income or Loss is the net income or loss determined for a Constituent Entity (before any consolidation adjustments eliminating intra-group transactions) in preparing Consolidated Financial Statements of the Ultimate Parent Entity. If it is not reasonably practicable to determine the Financial Accounting Net Income or Loss for a Constituent Entity based on the accounting standard used in the preparation of Consolidated Financial Statements of the Ultimate Parent Entity, the Financial Accounting Net Income or Loss for the Constituent Entity for the Fiscal Year may be determined using another Acceptable Financial Accounting Standard or an Authorised Financial Accounting Standard if: (a) the financial accounts of the Constituent Entity are maintained based on that accounting standard; (b) the information contained in the financial accounts is reliable; and (c) permanent differences in excess of EUR 1 million that arise from the application of a particular principle or standard to items of income or expense or transactions that differs from the financial standard used in the preparation of the Consolidated Financial Statements of the Ultimate Parent Entity are conformed to the treatment required under the accounting standard used in the Consolidated Financial Statements of the Ultimate Parent Entity."
    ],
    [
        "What is financial accounting net income or loss?",
        "The GloBE Income or Loss of each Constituent Entity is the Financial Accounting Net Income or Loss determined for the Constituent Entity for the Fiscal Year adjusted for the items described in Article 3.2 to Article 3.5. Financial Accounting Net Income or Loss is the net income or loss determined for a Constituent Entity (before any consolidation adjustments eliminating intra-group transactions) in preparing Consolidated Financial Statements of the Ultimate Parent Entity. If it is not reasonably practicable to determine the Financial Accounting Net Income or Loss for a Constituent Entity based on the accounting standard used in the preparation of Consolidated Financial Statements of the Ultimate Parent Entity, the Financial Accounting Net Income or Loss for the Constituent Entity for the Fiscal Year may be determined using another Acceptable Financial Accounting Standard or an Authorised Financial Accounting Standard if: (a) the financial accounts of the Constituent Entity are maintained based on that accounting standard; (b) the information contained in the financial accounts is reliable; and (c) permanent differences in excess of EUR 1 million that arise from the application of a particular principle or standard to items of income or expense or transactions that differs from the financial standard used in the preparation of the Consolidated Financial Statements of the Ultimate Parent Entity are conformed to the treatment required under the accounting standard used in the Consolidated Financial Statements of the Ultimate Parent Entity."
    ],
]
with torch.no_grad():
    inputs = tokenizer(pairs, padding=True, truncation=True, return_tensors='pt', max_length=512)
    scores = model(**inputs, return_dict=True).logits.view(-1, ).float()
    print(scores)
    end = time.perf_counter()  
    elapsed = end - start  
    print(f"Reranker ran in {elapsed:.2f} seconds")